### ISSUE TITLE
Pagina inaccesible

### ISSUE THREAD

**Issue by williamL3y35** [Launch-X-Latam/OnBoarding#5]
La pagina https://launchxauth.azurewebsites.net/joingh
No esta accesible
![Screenshot_2022-09-22-21-54-15-955_com android chrome](https://user-images.githubusercontent.com/68880300/191884492-06562c62-52ac-460f-9c71-758bf9e37427.jpg)

**Comment by ManuOSMx** [comment]
¡Hola @williamL3y35!
La página ya se encuentra nuevamente en funcionamiento para que puedan continuar con su OnBoarding. 🙌🏼

Un saludo.

**Comment by ManuOSMx** [comment]
¡Hola @williamL3y35!
La página ya se encuentra nuevamente en funcionamiento para que puedan continuar con la [Etapa 2 ](https://github.com/Launch-X-Latam/OnBoarding/blob/main/join_github/README.md#etapa-2-unirte-a-la-organizaci%C3%B3n-de-launch-x-latam)del **OnBoarding**. 🙌🏼

Un saludo.
